### ISSUE TITLE
Limit posting to one leaf per submit

### ISSUE THREAD

**Issue by nikolas** [mcfiredrill/forttree#34]
I accidentally clicked 'post' twice before the page reloaded, and two images were posted.

**Comment by mcfiredrill** [comment]
So usually for stuff like this I just disable the submit button on click.

**Comment by mcfiredrill** [comment]
something like
```
$("#button").on 'submit' ->
  $(this).attr('disabled', 'disabled')
```

**Comment by nikolas** [comment]
that would work, but isn't this something that can be done on the back-end? in general i prefer to do things there because it's easier to test.

**Comment by nikolas** [comment]
on second thought does this really matter... it's like super low priority... so many better things to spend our time on
