### ISSUE TITLE
[3d] image loading bug

### ISSUE THREAD

**Issue by nikolas** [mcfiredrill/forttree#39]
Freaking annoying.. I need to fix this.

![2015-05-05-163352_783x475_scrot](https://cloud.githubusercontent.com/assets/59292/7482327/9e79c2f2-f344-11e4-8568-001a8d1f7ec8.png)

> Image from origin 'http://s3.amazonaws.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.fortchan.org' is therefore not allowed access.

**Comment by mcfiredrill** [comment]
This is still an issue? I'm pretty sure we just have to set the right headers on S3...

**Comment by nikolas** [comment]
looks like it's working now

**Comment by nikolas** [comment]
![2017-05-24-234639_719x474_scrot](https://cloud.githubusercontent.com/assets/59292/26435169/4124eaa0-40db-11e7-80ef-080bbd2e6514.png)
