### ISSUE TITLE
buy this website

### ISSUE THREAD

**Issue by nikolas** [mcfiredrill/forttree#53]
![2016-08-19-124115_604x215_scrot](https://cloud.githubusercontent.com/assets/59292/17817063/6a401006-660a-11e6-9bda-0c0210818582.png)

what if i want to buy fortchan

**Comment by mcfiredrill** [comment]
How much dough we talkin here

![precious_yennies](https://cloud.githubusercontent.com/assets/66243/17828304/a6c9f2b2-66c8-11e6-862c-ca6683752a02.gif)

**Comment by nikolas** [comment]
75 big ones

**Comment by mcfiredrill** [comment]
sorry no can do

**Comment by nikolas** [comment]
👍
